spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/jpa
        username: root
        password: 1234
        driverClassName: org.mariadb.jdbc.Driver
    http:
        encoding:
            charset: UTF-8

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

    resources:
        chain:
            compressed: true
            cache: true

server:
    compression:
        enabled: true
    tomcat:
        uri-encoding: UTF-8
    error:
        whitelabel:
            enabled: true
            
logging:
    level:
        root: true

        
---

## Test configuration
spring:
    profiles: test
    datasource:
        url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
        username: sa
        password:
        driver-class-name: org.h2.Driver
        data: # classpath:sql/dml/... # DML
        schema: classpath:sql/ddl/schema.sql # DDL
        initialization-mode: ALWAYS 
    h2:
        console:
            enabled: true